version: '3.8'

services:
  # Just the dental calendar app - no LiveKit for now
  app:
    build:
      context: ./dental-calendar
      dockerfile: Dockerfile.simple
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3