version: '3.8'

services:
  # LiveKit Server - Simple dev mode
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
    command: --dev
    restart: unless-stopped

  # Dental Calendar Application
  dental-calendar:
    build:
      context: ./dental-calendar
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - LIVEKIT_URL=ws://livekit:7880
    depends_on:
      - livekit
    restart: unless-stopped