version: '3.8'

services:
  # LiveKit Server for WebRTC
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881/tcp"
      - "30000-40000:30000-40000/udp"
    environment:
      - LIVEKIT_KEYS=devkey:devsecret_that_is_at_least_32_characters_long
      - LIVEKIT_LOG_LEVEL=info
      - LIVEKIT_RTC_USE_ICE_LITE=true
      - LIVEKIT_RTC_PORT_RANGE_START=30000
      - LIVEKIT_RTC_PORT_RANGE_END=40000
    command: --dev --bind 0.0.0.0
    networks:
      - sofia-network
    restart: unless-stopped

  # Dental Calendar API
  dental-calendar:
    build:
      context: ./dental-calendar
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - LIVEKIT_URL=ws://${VPS_IP:-livekit}:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret_that_is_at_least_32_characters_long
      - PUBLIC_URL=http://${VPS_IP:-localhost}:3005
      - VPS_IP=${VPS_IP:-localhost}
    volumes:
      - calendar-data:/app/data
    networks:
      - sofia-network
    restart: unless-stopped
    depends_on:
      - livekit

  # Sofia Voice Agent
  sofia-agent:
    build:
      context: .
      dockerfile: Dockerfile.sofia
    environment:
      - LIVEKIT_URL=ws://livekit:7880
      - LIVEKIT_API_KEY=devkey
      - LIVEKIT_API_SECRET=devsecret_that_is_at_least_32_characters_long
      - GOOGLE_API_KEY=AIzaSyCGXSa68qIQNtp8WEH_zYFF3UjIHS4EW2M
      - CALENDAR_URL=http://dental-calendar:3005
      - HEALTH_CHECK_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - livekit
      - dental-calendar
    networks:
      - sofia-network
    restart: unless-stopped

  # CRM Dashboard
  crm-dashboard:
    build:
      context: ./crm
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - calendar-data:/app/data
    networks:
      - sofia-network
    restart: unless-stopped

  # Nginx Reverse Proxy with automatic config
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.production.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dental-calendar
      - livekit
      - sofia-agent
    networks:
      - sofia-network
    restart: unless-stopped

volumes:
  calendar-data:

networks:
  sofia-network:
    driver: bridge