#!/bin/bash
# Fix SSH connection issues

echo "SSH Connection Troubleshooting"
echo "=============================="
echo ""
echo "Try these solutions in order:"
echo ""
echo "1. Force close the stuck connection:"
echo "   Press Ctrl+C to exit the loop"
echo ""
echo "2. Use verbose mode to see what's happening:"
echo "   ssh -v root@167.235.67.1"
echo ""
echo "3. Try with specific options:"
echo "   ssh -o ConnectTimeout=10 -o ServerAliveInterval=5 root@167.235.67.1"
echo ""
echo "4. Clear SSH known hosts (if key changed):"
echo "   ssh-keygen -R 167.235.67.1"
echo "   Then try: ssh root@167.235.67.1"
echo ""
echo "5. Use password authentication explicitly:"
echo "   ssh -o PreferredAuthentications=password root@167.235.67.1"
echo ""
echo "6. Check if server is responding:"
echo "   ping 167.235.67.1"
echo "   nc -zv 167.235.67.1 22"
echo ""
echo "7. Alternative: Use a different terminal:"
echo "   - Try from a new terminal window"
echo "   - Use 'ssh -t root@167.235.67.1' for forced pseudo-terminal"
echo ""
echo "Common causes:"
echo "- SSH key issues"
echo "- Network problems"
echo "- Server SSH config changed"
echo "- Terminal encoding issues"