#!/bin/bash
# Fix firewall and restart services

echo "SSH to your VPS and run these commands:"
echo ""
echo "# 1. Allow port 3005 through firewall"
echo "ufw allow 3005/tcp"
echo "ufw allow 80/tcp"
echo "ufw allow 443/tcp"
echo "ufw allow 22/tcp"
echo "ufw --force enable"
echo ""
echo "# 2. Check if the server is still running"
echo "ps aux | grep 'python3.*3005'"
echo ""
echo "# 3. If not running, start it again"
echo "cd /root/elo-deu/dental-calendar/public"
echo "nohup python3 -m http.server 3005 > /dev/null 2>&1 &"
echo ""
echo "# 4. Check nginx is pointing to the right port"
echo "cat /etc/nginx/sites-available/elosofia.site"
echo ""
echo "# 5. Test locally on VPS"
echo "curl http://localhost:3005"