#!/bin/bash
# Install Claude CLI on VPS

echo "Installing Claude CLI on VPS..."
echo ""
echo "SSH to your VPS and run these commands:"
echo ""
echo "# 1. Install using npm (recommended)"
echo "npm install -g @anthropic-ai/claude-cli"
echo ""
echo "# 2. Or using the install script"
echo "curl -fsSL https://console.anthropic.com/install.sh | sh"
echo ""
echo "# 3. Set your API key"
echo "export ANTHROPIC_API_KEY='your-api-key-here'"
echo "echo 'export ANTHROPIC_API_KEY=\"your-api-key-here\"' >> ~/.bashrc"
echo ""
echo "# 4. Test it"
echo "claude --version"
echo "claude 'Hello from VPS!'"
echo ""
echo "Benefits:"
echo "- Direct file editing on VPS"
echo "- No SSH connection issues"
echo "- Faster deployment updates"
echo "- Can run background tasks"