# LiveKit TCP-Only Configuration for Global Access
# This forces all WebRTC traffic through TCP, making it work everywhere

# Logging
log_level: info
logging:
  json: false
  level: info

# RTC Configuration - TCP Only
rtc:
  # Force TCP transport
  use_ice_lite: true
  
  # TCP port for WebRTC
  tcp_port: 7881
  
  # Disable UDP ports completely
  port_range_start: 0
  port_range_end: 0
  
  # TURN configuration
  turn:
    enabled: true
    # Use external TURN server
    external_turn:
      - host: localhost
        port: 3478
        protocol: tcp
        username: test
        credential: test
    
  # Interfaces to use
  interfaces:
    - en*
    - eth*
    - wl*

  # Congestion control for TCP
  congestion_control:
    enabled: true
    
  # Allow TCP fallback
  allow_tcp_fallback: true

# Room settings
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 50

# WebRTC settings optimized for TCP
webrtc:
  tcp_mux:
    enabled: true
    port: 7881

# Keys for authentication (same as before)
keys:
  devkey: secret

# Webhook (optional)
webhook:
  api_key: secret

# Health check
health_check:
  enabled: true
  port: 7882