[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python agent.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[[services]]
name = "sofia-agent"
targetPort = 8080

[services.sofia-agent]
healthcheckPath = "/health"
healthcheckInterval = 30