# LiveKit Production Configuration
port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  enable_loopback_candidate: false
  
redis:
  address: redis:6379
  
webhook:
  urls:
    - http://sofia-agent:8080/webhook
    
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 10
  
turn:
  enabled: true
  domain: turn.livekit.cloud
  cert_file: ""
  key_file: ""
  tls_port: 5349
  udp_port: 3478
  external_tls: true
  
logging:
  level: info
  sample: false
  
keys:
  devkey: secret