# LiveKit server configuration
port: 7880
bind_addresses:
  - "0.0.0.0"

rtc:
  tcp_port: 7881
  port_range:
    start: 50000
    end: 60000
  use_external_ip: true
  # Stun servers for NAT traversal
  stun_servers:
    - "stun:stun.l.google.com:19302"
    - "stun:stun1.l.google.com:19302"
  # Enable TURN relay for better connectivity
  turn:
    enabled: true
    domain: elosofia.site
    protocol: udp
    port: 3478
    
# Redis for distributed mode and session storage
redis:
  address: redis:6379
  use_tls: false
  
# Logging configuration
logging:
  level: info
  json: true
  
# Room configuration
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 50
  
# WebRTC configuration
webrtc:
  # Enable simulcast for better quality adaptation
  simulcast: true
  # Enable dynacast for bandwidth optimization
  dynacast: true
  
# Security
keys:
  # API key will be injected via environment variable
  
# Webhook configuration for room events
webhook:
  urls:
    - http://sofia-agent:8080/webhook/livekit
  
# Health check endpoint
health_check:
  enabled: true
  port: 8080